<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="ITG_Tsk2.WebForm1" MasterPageFile="~/Site.Master" %>

<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
    <!DOCTYPE html>



    <div>

        <asp:TextBox ID="txtSearch" runat="server" Placeholder="Search"></asp:TextBox>
        <asp:Button ID="btnSearch" runat="server" Text="Search" CssClass="btn btn-success" OnClick="btnSearch_Click" />

        <div>

            <br />
            <asp:GridView ID="Gv1" AllowPaging="True" CssClass="mydatagrid"
                HeaderStyle-CssClass="header" RowStyle-CssClass="rows" DataKeyNames="User_id" ShowFooter="true" OnPageIndexChanging="Gv1_PageIndexChanging" OnRowCreated="Gv1_RowCreated1" runat="server" AutoGenerateColumns="False"  OnRowDeleting="Gv1_RowDeleting" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowEditing="Gv1_RowEditing1" OnRowUpdating="Gv1_RowUpdating1" OnRowCancelingEdit="Gv1_RowCancelingEdit1" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowDataBound="Gv1_RowDataBound" OnSelectedIndexChanged="Gv1_SelectedIndexChanged" AllowSorting="true" OnSorting="Gv1_Sorting">

                <AlternatingRowStyle BackColor="White" />
               



                <Columns>
                    <%--                     
    <asp:CommandField ShowDeleteButton="true" DeleteText="Delete" HeaderText="Delete" ButtonType="Button" ControlStyle-CssClass="btn btn-danger"  />--%>

                    <asp:TemplateField SortExpression="User_id" Visible="false" HeaderText="Id">

                        <EditItemTemplate>

                            <asp:TextBox ID="txtUID" Text='<%#Eval("User_id") %>' runat="server"></asp:TextBox>
                        </EditItemTemplate>

                        <ItemTemplate>
                            <asp:Label ID="lblUID" runat="server" Text='<%#Eval("User_id") %>'></asp:Label>
                        </ItemTemplate>

                    </asp:TemplateField>

                    <asp:TemplateField SortExpression="Name" HeaderText="Name">


                        <EditItemTemplate>
                            <asp:TextBox ID="txtN" Text='<%#Eval("Name") %>' runat="server"></asp:TextBox>
                        </EditItemTemplate>


                        <ItemTemplate>

                            <asp:Label ID="lblN" runat="server" Text='<%#Eval("Name") %>'></asp:Label>
                        </ItemTemplate>

                    </asp:TemplateField>


                    <asp:TemplateField SortExpression="UserName" HeaderText="UserName">

                        <EditItemTemplate>

                            <asp:TextBox ID="txtUserN" Text='<%#Eval("UserName") %>' runat="server"></asp:TextBox>



                        </EditItemTemplate>

                        <ItemTemplate>

                            <asp:Label ID="lblUserN" runat="server" Text='<%#Eval("UserName") %>'></asp:Label>

                        </ItemTemplate>

                    </asp:TemplateField>

                    <asp:TemplateField SortExpression="Gender" HeaderText="Gender">

                        <EditItemTemplate>

                            <asp:DropDownList ID="DDG" runat="server">

                                <asp:ListItem Text="Male" Value="1" Selected="true" name="Male"></asp:ListItem>
                                <asp:ListItem Text="Female" Value="2" name="Female"></asp:ListItem>
                                <asp:ListItem Text="Other" Value="3" name="Other"></asp:ListItem>
                            </asp:DropDownList>

                        </EditItemTemplate>

                        <ItemTemplate>
                            <asp:Label ID="lblGender" runat="server" Text='<%# Eval("Gender") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="User Type">
                        <EditItemTemplate>
                            <asp:DropDownList ID="DDUT" runat="server" SelectedValue='<%# Bind("UserTypeID") %>'>
                                <asp:ListItem Text="Admin" Value="1" name="Admain"></asp:ListItem>
                                <asp:ListItem Text="User" Value="2" name="User"></asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblUserType" runat="server" Text='<%# Eval("UserType") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField SortExpression="date_of_birth" HeaderText="DateOfBirth">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtDateOf" Text='<%#Eval("date_of_birth") %>' runat="server"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDateOf" runat="server" Text='<%#Eval("date_of_birth") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Language">
                        <EditItemTemplate>
                            <asp:DropDownList ID="DDL" runat="server" SelectedValue='<%# Bind("LanguageID") %>'>
                                <asp:ListItem Text="English" Value="1" name="English"></asp:ListItem>
                                <asp:ListItem Text="Arabic" Value="2" name="Arabic"></asp:ListItem>
                                <asp:ListItem Text="French" Value="3" name="French"></asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblLanguage" runat="server" Text='<%# Eval("Language") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                         <FooterTemplate>
        
                    <div  >
           
                        <asp:Label ID="lblRowCount" runat="server"></asp:Label>
       
                        </div>
    
                </FooterTemplate>
                    </asp:TemplateField>
                     

                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
                
                   
                
              

                

                
            </asp:GridView>
        </div>
        <br />
        <%--<br />--%>
  <asp:Panel ID="InsertForm" runat="server">
    <div class="form-row">
        <div class="form-group col-md-4">
            <div class="input-group" >
                <asp:Label ID="lblAddName" runat="server" AssociatedControlID="txtAddName" CssClass="inside-lbl">Name*</asp:Label>
                <asp:TextBox style="margin-left:38px" ID="txtAddName" runat="server" CssClass="form-control" placeholder="Name"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" CssClass="error-message" ControlToValidate="txtAddName" runat="server" ErrorMessage="Please fill Name*"></asp:RequiredFieldValidator>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="input-group">
                <asp:Label style="margin-right:10px" ID="lblAddUserName" runat="server" AssociatedControlID="txtAddUserName" CssClass="inside-lbl">Username*</asp:Label>
                <asp:TextBox CssClass="form-control" ID="txtAddUserName" runat="server" placeholder="Username"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" CssClass="error-message" ControlToValidate="txtAddUserName" ErrorMessage="Please fill Username"></asp:RequiredFieldValidator>
                <asp:RegularExpressionValidator ID="RegularExpressionValidator2" CssClass="error-message" ControlToValidate="txtAddUserName" runat="server" ErrorMessage="Please enter a valid email address" ValidationExpression="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"></asp:RegularExpressionValidator>
                <asp:RegularExpressionValidator ID="RegularExpressionValidator1" ControlToValidate="txtAddUserName" CssClass="error-message" ValidationExpression="[^\s]+$" runat="server" ErrorMessage="Username should not contain spaces"></asp:RegularExpressionValidator>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <div class="input-group">
                <asp:Label ID="lblGender" runat="server" AssociatedControlID="DDG" CssClass="inside-lbl">Gender*</asp:Label>
                <asp:DropDownList style="margin-left:29px" ID="DDG" runat="server" CssClass="form-control">
                    <asp:ListItem Text="Select Gender" Value="" Disabled="true" Selected="true"></asp:ListItem>
                    <asp:ListItem Text="Male" name="Male" Value="1" />
                    <asp:ListItem Text="Female" name="Female" Value="2" />
                </asp:DropDownList>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" CssClass="error-message" ControlToValidate="DDG" InitialValue="" runat="server" ErrorMessage="Please select Gender*"></asp:RequiredFieldValidator>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="input-group">
                <asp:Label ID="lblUserType" runat="server" AssociatedControlID="DDU" CssClass="inside-lbl">UserType*</asp:Label>
                <asp:DropDownList style="margin-left:16px" ID="DDU" runat="server" CssClass="form-control">
                    <asp:ListItem Text="UserType" Value="" Disabled="true" Selected="true"></asp:ListItem>
                    <asp:ListItem Text="Admin" name="Admin" Value="1" />
                    <asp:ListItem Text="User" name="User" Value="2" />
                </asp:DropDownList>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" CssClass="error-message" ControlToValidate="DDU" runat="server" ErrorMessage="Please select UserType*"></asp:RequiredFieldValidator>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <div class="input-group">
                <asp:Label ID="lblBirthDate" runat="server" AssociatedControlID="txtBirth" CssClass="inside-lbl">Birth Date*</asp:Label>
                <asp:TextBox ID="txtBirth" style="margin-left:10px" runat="server" placeholder="BirthOfDate" CssClass="form-control" type="Date"></asp:TextBox>
                <asp:RequiredFieldValidator ErrorMessage="Please fill Birth Date*" CssClass="error-message" ControlToValidate="txtBirth" runat="server"></asp:RequiredFieldValidator>
                <asp:RangeValidator ID="RangeValidator1" Type="Date" ControlToValidate="txtBirth" MinimumValue="2000-01-01" MaximumValue="2060-01-01" runat="server" CssClass="error-message" ErrorMessage="Please enter a valid date between 18 and 55 years old"></asp:RangeValidator>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="input-group">
                <asp:Label ID="lblLanguage" runat="server" AssociatedControlID="DDLanguge" CssClass="inside-lbl">Language*</asp:Label>
                <asp:DropDownList style="margin-left:10px" ID="DDLanguge" runat="server" CssClass="form-control">
                    <asp:ListItem Text="Select Language" Value="" Disabled="true" Selected="true"></asp:ListItem>
                    <asp:ListItem Text="English" name="English" Value="1" />
                    <asp:ListItem Text="Arabic" name="Arabic" Value="2" />
                </asp:DropDownList>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator5" CssClass="error-message" ControlToValidate="DDLanguge" runat="server" ErrorMessage="Please select Language*"></asp:RequiredFieldValidator>
            </div>
        </div>
    </div>
    <div class="form-group">
        <asp:Button ID="btnAdd" runat="server" Text="Add" CssClass="btn btn-success" OnClick="btnAdd_Click" OnClientClick="showAlert();" />
    </div>
</asp:Panel>


    <script>
        function showAlert() {
            alert("User added successfully!");
        }
    </script>
    </div>
</asp:Content>
